# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likeit',
        ),
    ]
