# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-date_pub',)},
        ),
    ]
